### ISSUE TITLE
Server Version

### ISSUE THREAD

**Issue by theminecoder** [CraftTogether/Discussion-Issues#1]
So for our first discussion, I would like to know the version of the server that we will be running on (to start with anyway), either 1.8 or 1.9?

Add a :+1: reaction on the comments below to cast your votes!

**Comment by theminecoder** [comment]
1.8

**Comment by theminecoder** [comment]
1.9

**Comment by theminecoder** [comment]
1.8 (with via version for 1.9 protocol hack)

**Comment by SpiderRobotMan** [comment]
I'd do 1.9 personally. I like the new features it adds.

**Comment by DiMuRie** [comment]
Let's wait for the first 1.10 snapshot

**Comment by theminecoder** [comment]
Alright, I think we have an overwhelming winner here, so I am going to close this and start working on getting the initial project structure up!
