### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by oliverdunk** [CraftTogether/Discussion-Issues#11]
Vote below (using thumbs up reaction)! I'm personally for Java 8 as it's good to keep up to date and will also provide a great learning experience for anyone who hasn't made use of the features before.

**Comment by oliverdunk** [comment]
Java 7

**Comment by oliverdunk** [comment]
Java 8

**Comment by theminecoder** [comment]
Side note: The servers themselves will run Java 8, but for a code standard you can chose to use it or not

**Comment by Musician101** [comment]
Vanilla Minecraft and PaperSpigot both use Java 8 as well. Vanilla even downloads and uses a preset Java 8 version until the user goes in and manually changes it.

**Comment by theminecoder** [comment]
Java 8 it is!
