### ISSUE TITLE
Server Software?

### ISSUE THREAD

**Issue by Rushmead** [CraftTogether/Discussion-Issues#2]
Thought i'd start this discussion so we can get this thing moving!

What server software should we use?

Spigot
PaperSpigot
TacoSpigot
Sponge

**Comment by theminecoder** [comment]
I'm heading more toward PaperSpigot, how ever I didn't even know that TacoSpigot existed. Will be taking a look into it. Also going to tag @CraftTogether/operations on this one.

**Comment by Rushmead** [comment]
My Personal opinion would be to go PaperSpigot because of the awesome optimizations however if we plan on using lots of armor stands then TacoSpigot has good optimizations for them

**Comment by Desetude** [comment]
I think it'd be nice if we went with sponge as it has a more modern API, has high quality documentation and now has a larger feature set than the other options, meaning less use of NMS. It isn't being used largely at the moment but that shouldn't be a problem if we're making this server from scratch.  Although I'm happy with using any of the other options too.

**Comment by Rushmead** [comment]
I'm not convinced by Sponge, i'm sure it would be a learning experience for most people(Possibly wrong) but i think it really depends on what we want to be able to do with the server

**Comment by Flame10A** [comment]
At a glance, I'd agree on PaperSpigot. Taco has a few further optimizations, but knowing that even basic Spigot is sufficient for most things, I don't think we'd need to go that far. I can't speak for Sponge, as I've never touched it, but from taking a quick look around, I haven't seen any major reason to switch there from the Spigot line.

**Comment by WilliamBurns** [comment]
I don't think using Sponge is a good idea. Some version of Spigot would be nicer imo.

**Comment by theminecoder** [comment]
Alright, I think that I will go with the general consensus here and settle with PaperSpigot
