### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by theminecoder** [CraftTogether/Discussion-Issues#4]
So I would like to know, what database would you all like to use for the main storage.

Some options:
- MongoDB
- MySQL/MariaDB
- RethinkDB

**Comment by andy1ne0** [comment]
I'm in favor of Rethink - while I'm more familiar with SQL, Rethink would be better in terms of performance -- and the Java driver also looks relatively easy to learn/use.

**Comment by jakeycodes22222222** [comment]
RethinkDB Flexible to what we need it to do

**Comment by erosemberg** [comment]
MONGOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo

**Comment by jakeycodes22222222** [comment]
@erosemberg You love MongoDb Dont you

**Comment by theminecoder** [comment]
Just a little bit it seems :joy:

**Comment by GingerGeek** [comment]
Mongo and MySQL, they are good for different things. Haven't heard of rethink so can't comment.

**Comment by theminecoder** [comment]
@GingerGeek https://www.rethinkdb.com/

**Comment by AKTheKnight** [comment]
Rethink seems like the best option

**Comment by Rushmead** [comment]
Rethinkdb is good!

**Comment by theminecoder** [comment]
Alright rethink looks to be the winner here, so I will mark this as closed!

**Comment by erosemberg** [comment]
@theminecoder Bad coder.

**Comment by theminecoder** [comment]
@erosemberg Have you seen rethink? It's kinda like mongo with some realtime functions thrown on top
