### ISSUE TITLE
Bungee Software

### ISSUE THREAD

**Issue by Rushmead** [CraftTogether/Discussion-Issues#6]
Do we want have a Bungee System?

If so do we want to use Bungee or Waterfall or even our own fork?

**Comment by theminecoder** [comment]
I was going to put it behind a bungee either way :P But yeh I guess we need to figure our what software want for it.

+1 for Waterfall

**Comment by Rushmead** [comment]
Cool, i also +1 for Waterfall, however a custom Fork may be useful for custom messages and such.

**Comment by theminecoder** [comment]
There is a plugin (will have to find it again) that allows for editing the default messages, so we can just use that
